### ISSUE TITLE
cannot reshape array of size 0 into shape (64,128,128,1)

### ISSUE THREAD

**Issue by AndrewSoul** [lmb-freiburg/mv3d#1]
When I tried to run bg_nodm.py, it has something wrong:
          ValueError: cannot reshape array of size 0 into shape (64,128,128,1)
    Maybe  three is something wrong : mask.astype(dtype=np.float32).reshape(
                        self.resolution, self.resolution, 1), im) 
                and
                  full_output = np.concatenate( (cl2, mask.reshape(self.batch_size, 128, 128, 1)), axis=3)

**Comment by mtatarchenko** [comment]
Could you please provide some extra information about the issue? Did you run the script in train or test mode? Did you download the additional materials (data/snapshots/backgrounds) before running the script?

**Comment by z362194037** [comment]
@AndrewSoul do you solve the issue? I get the same question

**Comment by AndrewSoul** [comment]
Emm...No, I don't..
On 08/03/2017 17:37, z362194037 wrote:

@AndrewSoul do you solve the issue? I get the same question

**Comment by z362194037** [comment]
@AndrewSoul  I think change the  path="../data"  into your own path such as "home/xxx/xxx/data"       in def load_test_set(normal, bg, rad_factor=1000.0)which in  tf_utils.py  work.

**Comment by mtatarchenko** [comment]
@z362194037 Thank you for pointing this out. The data path was relative to the working directory, not the script location. I've updated the corresponding section of the code.
