### ISSUE TITLE
inconsistent fc output size

### ISSUE THREAD

**Issue by guofeisun** [lmb-freiburg/mv3d#10]
Hi, your work is impressive. When I read the paper, I found inconsistent fc layer output size ( 1024 in the paper vs 4096 in the code). So which one do you choose finally.

**Comment by tatarchm** [comment]
Indeed, the model in the repository is a bit different from the one described in the paper - we mention it in the README file. According to our experience, increasing the size of the hidden code from 1024 to 4096 produces slightly better results but the improvement is not particularly significant.
