### ISSUE TITLE
Panda3D obj2egg utility does not support .mtl textures

### ISSUE THREAD

**Issue by airalcorn2** [lmb-freiburg/mv3d#12]
From what I could find on [the Panda3D forums](https://discourse.panda3d.org/t/obj-no-texture/15304), the `obj2egg` utility does not support textures/`.mtl` files. So, for example, converting the ShapeNet object `ShapeNetCore/02958343/114b662c64caba81bb07f8c2248e54bc` (a "NYPD Highway Patrol Dodge Charger") to a BAM file using:

```bash
obj2egg model_normalized.obj model_normalized.egg
egg2bam model_normalized.egg model_normalized.bam
```

and then running the following code:

```python
from PIL import Image
from renderer import Renderer
from panda3d.core import VBase4

renderer = Renderer(False, False)
renderer.alight.setColor(VBase4(1, 1, 1, 1))
renderer.models = renderer.loader.loadModel(["model_normalized.bam"])
renderer.selectModel(0)

lights = [[3.5, 0, 60, 13]]

rad = 2.0
el = 15
az = 60
blur = 0
blending = 0

(im, dm) = renderer.renderView(
    [rad, el, az], lights, blur, blending, default_bg_setting=0
)

image = Image.fromarray(im)
image.show()
```

produces this as output:

![no_texture](https://user-images.githubusercontent.com/1927770/54480656-e28f1480-47f8-11e9-9e4c-cc00ec4e812d.png)

@treeform's forked `obj2egg` tool found [here](https://github.com/treeform/obj2egg) seems to add support for textures, but has not been updated in almost 10 years. Can you share the exact steps you were doing to convert the objects?

**Comment by airalcorn2** [comment]
I've attempted to update @treeform's `obj2egg` fork [here](https://github.com/airalcorn2/mv3d/commit/dc54c38391c21347b4e22abf46b7043e4aa75ddc). Running:

```bash
python3 obj2egg.py model_normalized.obj
egg2bam model_normalized.egg model_normalized.bam
```

and then running the same script from above produces the below output:

![with_texture](https://user-images.githubusercontent.com/1927770/54480804-153a0c80-47fb-11e9-86c2-8248db9d9906.png)

which seems like an improvement, but is still not optimal. Compare to the render produced by [my own tool](https://github.com/airalcorn2/strike-with-a-pose), which uses [ModernGL](https://github.com/cprogrammer1994/ModernGL) for the graphics backend and my own `.obj`/`.mtl` parsers:

![my_texture](https://user-images.githubusercontent.com/1927770/54480841-a4dfbb00-47fb-11e9-904e-9687d5139e07.png)

**Comment by treeform** [comment]
Wow blast from the past.

**Comment by airalcorn2** [comment]
I was able to get the ShapeNet car models [rendering properly](https://github.com/ShapeNet/shapenet-viewer/issues/28#issuecomment-473739297) in my own tool, so I'll just use it.
