### ISSUE TITLE
AttributeError: mv3d instance has no attribute 'writer'

### ISSUE THREAD

**Issue by z362194037** [lmb-freiburg/mv3d#3]
I run the nobg_nodm.py , it has something wrong:
Traceback (most recent call last):
  File "nobg_nodm.py", line 191, in <module>
    net.test(0)
  File "nobg_nodm.py", line 136, in test
    log_value(self.writer, total_loss, 'test_loss', global_iter)
AttributeError: mv3d instance has no attribute 'writer'
I run in test mode and I downloaded the data and snapshots.What's the problem?

**Comment by tatarchm** [comment]
Fixed. Btw, the code was initially written for an older TensorFlow 0.12. I will try to make it compatible with the new API when I get a chance.
