### ISSUE TITLE
unable to render examples

### ISSUE THREAD

**Issue by kana-mycin** [lmb-freiburg/mv3d#4]
Hi, I'm attempting to re-implement the code from the mv3d work as part of a different project. I am using the script utils/render_test_set.py (with modifications for locating the file paths) to render examples, but while the depth maps appear to render correctly, the rgb images render as simple black and white silhouettes. Any insight on why this may be the case? We are using OpenGL, the default rendering mode for Panda3D.

One of the obj models:
<img width="575" alt="screen shot 2017-11-19 at 5 56 03 pm" src="https://user-images.githubusercontent.com/7535490/32998812-0819fa84-cd53-11e7-84aa-397c8bc866c3.png">

Rendered output:
![000_cl_0_19_284_16](https://user-images.githubusercontent.com/7535490/32998761-a82c329a-cd52-11e7-9da3-44e6e20e33c1.png)

**Comment by tatarchm** [comment]
I'm afraid I won't be able to assist with this. It works in my setup, which is Panda3D 1.9.1 + Python 2. Do you have the same configuration? I'm no expert on Panda3D, and cannot tell what possible problems it may run into.

**Comment by MalihaUCF** [comment]
@tatarchm  do you get rendered RGB images at this point? 

cl1, dm1, cl2, dm2, lb = self.rend.render(100.0) in train() function.

or there is some more post processing,I have the same problem as @kana-mycin . I also get rendered segmentation mask and I am not sure how to get RGB images from there, please help .

**Comment by kana-mycin** [comment]
This was a while ago so I don't remember exactly, but I think I eventually figured out the reason for this issue. The problem was that I was trying to use a graphics API that wasn't the default OpenGL, because I wasn't running on a GPU. I think once I switched to a GPU cluster it worked fine.

Maybe check your panda3d configuration, or switch to a machine that supports OpenGL/has a GPU.

**Comment by MalihaUCF** [comment]
thank you @kana-mycin , I will try this and update

**Comment by MalihaUCF** [comment]
Hi @kana-mycin , it doesnt work.I think the new panda library 1.9.4 doesnt use this function to generate colored images (textureToImage) or something, problem is probably here, since we get the uncolored image here only.

 def renderView(self, camera_pos, light_sources,
                   blur, blending, spher=True, default_bg_setting=True):

        self.setCameraPosition(camera_pos[0],
                               math.radians(camera_pos[1]),
                               math.radians(camera_pos[2]))

        self.activateLightSources(light_sources, spher)

        base.graphicsEngine.renderFrame()
        tex = base.win.getScreenshot()
        im = self.textureToImage(tex)
